### ISSUE TITLE
Don't onebox /edits links

### ISSUE THREAD

**Issue by Freso** [phw/discourse-musicbrainz-onebox#8]
See http://chatlogs.metabrainz.org/brainzbot/musicbrainz/msg/3561919/

It seems weird that a link to an entity's edits makes a onebox for the entity. I'm guessing it's just https://github.com/phw/discourse-musicbrainz-onebox/blob/master/engine/musicbrainz.rb#L87 that needs to be tweaked, but I'm not feeling like poking at it myself right now. :)

**Comment by phw** [comment]
Actually this was intentional. My thinking was that it would be confusing that some of the many links to an entity would give you the onebox, other don't. E.g. linking to http://musicbrainz.org/artist/10bf95b6-30e3-44f1-817f-45762cdc0de0/details or indeed any of the tabs of the artist's page seems completely common to me and I would expect to see the onebox.

If we really want to limit this to the main page only tweaking the regex to:

```
/^https?:\/\/(?<domain>(?:beta\.)?musicbrainz\.org)\/#{Regexp.escape(entity)}\/(?<mbid>[0-9a-z-]+)\/?$/
```

should do the trick. Or we define a list of subpages that are allowed, but again I think it is confusing to allow some but not all.

**Comment by Freso** [comment]
Hm. Perhaps at least pull in the title then? "[Relationships|Details|Edits|Map|…] for [Artist|Event|…] [$entity_name]" or something? So it's clear what "kind" of link it is.

**Comment by Freso** [comment]
I did consider those other subpages, but since they can be accessed by an anonymous user as well, I didn't think they needed special casing, but the /edits page can only be accessed by a logged in user.
